version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: x-wetland-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=x_wetland
    volumes:
      - ./config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
